codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: true

ignore:
  - app
  - test
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 5%
