include(ExternalProject)

# Root directories for all external builds/installs
set(ITLABAI_EXTERNAL_ROOT "${CMAKE_BINARY_DIR}/_external" CACHE PATH "Root for external project builds")
set(ITLABAI_EXTERNAL_BUILD_ROOT "${ITLABAI_EXTERNAL_ROOT}/build" CACHE PATH "External build trees")
set(ITLABAI_EXTERNAL_INSTALL_ROOT "${ITLABAI_EXTERNAL_ROOT}/install" CACHE PATH "External install trees")

set(ITLABAI_EXTERNAL_TOOLCHAIN_ARGS "")
set(_itlabai_cc "")
set(_itlabai_cxx "")
if(DEFINED CMAKE_C_COMPILER AND NOT CMAKE_C_COMPILER STREQUAL "")
    set(_itlabai_cc "${CMAKE_C_COMPILER}")
elseif(DEFINED ENV{CC} AND NOT "$ENV{CC}" STREQUAL "")
    set(_itlabai_cc "$ENV{CC}")
endif()
if(DEFINED CMAKE_CXX_COMPILER AND NOT CMAKE_CXX_COMPILER STREQUAL "")
    set(_itlabai_cxx "${CMAKE_CXX_COMPILER}")
elseif(DEFINED ENV{CXX} AND NOT "$ENV{CXX}" STREQUAL "")
    set(_itlabai_cxx "$ENV{CXX}")
endif()
if(_itlabai_cc)
    list(APPEND ITLABAI_EXTERNAL_TOOLCHAIN_ARGS -DCMAKE_C_COMPILER=${_itlabai_cc})
endif()
if(_itlabai_cxx)
    list(APPEND ITLABAI_EXTERNAL_TOOLCHAIN_ARGS -DCMAKE_CXX_COMPILER=${_itlabai_cxx})
endif()

add_custom_target(itlabai_external) # aggregator for externals

include(${CMAKE_CURRENT_LIST_DIR}/deps/tbb.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/deps/onednn.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/deps/opencv.cmake)
if(ITLABAI_ENABLE_KOKKOS)
    include(${CMAKE_CURRENT_LIST_DIR}/deps/kokkos.cmake)
else()
    if(NOT TARGET Kokkos_imported)
        add_library(Kokkos_imported INTERFACE IMPORTED GLOBAL)
    endif()
endif()
include(${CMAKE_CURRENT_LIST_DIR}/deps/gtest.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/deps/json.cmake)

# Compatibility aliases for existing target names
if(NOT TARGET TBB_unified)
    add_library(TBB_unified INTERFACE IMPORTED GLOBAL)
    target_link_libraries(TBB_unified INTERFACE TBB::tbb)
endif()
