# Common helper functions and defaults for project targets

function(itlabai_target_defaults target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive- /EHsc)
        if(ITLABAI_WARN_AS_ERROR)
            target_compile_options(${target_name} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
        if(ITLABAI_WARN_AS_ERROR)
            target_compile_options(${target_name} PRIVATE -Werror)
        endif()
    endif()
    target_compile_features(${target_name} PRIVATE cxx_std_20)
endfunction()

function(itlabai_link_externals target_name)
    get_target_property(_tgt_type ${target_name} TYPE)
    if(_tgt_type STREQUAL "INTERFACE_LIBRARY")
        set(_scope INTERFACE)
    else()
        set(_scope PUBLIC)
    endif()
    set(_ext_map
        "opencv;OpenCV::opencv_world"
        "tbb;TBB_unified;TBB::tbb"
        "onednn;dnnl"
        "kokkos;Kokkos_imported"
        "openmp;OpenMP::OpenMP_CXX"
        "gtest;gtest_main;gtest"
    )
    foreach(ext IN LISTS ARGN)
        foreach(pair IN LISTS _ext_map)
            list(GET pair 0 key)
            if(ext STREQUAL key)
                list(REMOVE_AT pair 0)
                foreach(dep IN LISTS pair)
                    if(TARGET ${dep})
                        target_link_libraries(${target_name} ${_scope} ${dep})
                    endif()
                endforeach()
                if(TARGET ${ext}_external)
                    add_dependencies(${target_name} ${ext}_external)
                endif()
                if(ITLABAI_AUTOINCLUDE_EXTERNALS)
                    if(ext STREQUAL "tbb" AND DEFINED TBB_INSTALL_DIR)
                        target_include_directories(${target_name} ${_scope} $<BUILD_INTERFACE:${TBB_INSTALL_DIR}/include>)
                    endif()
                    if(ext STREQUAL "kokkos" AND DEFINED KOKKOS_INSTALL_DIR)
                        target_include_directories(${target_name} ${_scope} $<BUILD_INTERFACE:${KOKKOS_INSTALL_DIR}/include>)
                    endif()
                    if(ext STREQUAL "gtest" AND DEFINED GTEST_INSTALL_DIR)
                        target_include_directories(${target_name} ${_scope} $<BUILD_INTERFACE:${GTEST_INSTALL_DIR}/include>)
                    endif()
                    if(ext STREQUAL "opencv" AND DEFINED OPENCV_INSTALL_DIR)
                        target_include_directories(${target_name} ${_scope} $<BUILD_INTERFACE:${OPENCV_INSTALL_DIR}/include/opencv4>)
                    endif()
                endif()
            endif()
        endforeach()
    endforeach()
endfunction()

function(itlabai_set_rpath)
    set(_paths ${ARGN})
    list(REMOVE_DUPLICATES _paths)
    if(_paths)
        set(CMAKE_BUILD_RPATH "${_paths}" PARENT_SCOPE)
        set(CMAKE_INSTALL_RPATH "${_paths}" PARENT_SCOPE)
        set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE PARENT_SCOPE)
        set(CMAKE_SKIP_BUILD_RPATH FALSE PARENT_SCOPE)
        set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE PARENT_SCOPE)
    endif()
endfunction()
