name: Static analysis

on: [pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-${{ github.job }}
    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        apt_packages: libomp-dev,libopencv-dev
        build_dir: build
        cmake_command: cmake -S . -B build \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        config_file: .clang-tidy
        exclude: 3rdparty
        split_workflow: false
        lgtm_comment_body: ""
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
